#include<iostream>
using namespace std;
int main(){
for(int i=1;i<5;i++){
    for(int j=0;j<=i;j++){
        cout<<"*";
    }cout<<endl;
}
    return 0;
}











  //unstructured table of 2
    // #include<iostream>
    // using namespace std;
    // int main(){
    //     int num=2;
    //     for(int i=1;i<=10;i++){
    //         cout<<num*i<<endl;
    //     }

    //     return 0;
    // }




//for standard table making

//     #include <iostream>

// using namespace std;

// int main() {
//    int num = 2;
   
//    for (int i = 1; i <= 10; i++) {
//       cout << num << " x " << i << " = " << num*i << endl;
//    }
   
//    return 0;
// }
